name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  google_fonts: ^8.0.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/en.json
    - assets/i18n/fr.json
    - assets/images/first_page_icon.svg
    - assets/images/email_icon.svg
    - assets/images/linkedin_logo.svg
    - assets/images/joblyx_logo.png
    - assets/images/processing.svg

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
