"""add generation_status to career

Revision ID: 02c931570ab0
Revises: 76d019d9efce
Create Date: 2026-03-06 20:46:29.399712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c931570ab0'
down_revision: Union[str, Sequence[str], None] = '76d019d9efce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career', sa.Column('generation_status', sa.String(length=20), server_default='idle', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career', 'generation_status')
    # ### end Alembic commands ###
