"""restructure roadmaps with roadmap_phases table

Revision ID: 141656253150
Revises: 9ed5c7d9d05d
Create Date: 2026-03-20 12:31:44.852108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '141656253150'
down_revision: Union[str, Sequence[str], None] = '9ed5c7d9d05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_phases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('milestone', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('custom', sa.Boolean(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_phases_roadmap_id'), 'roadmap_phases', ['roadmap_id'], unique=False)
    op.add_column('roadmaps', sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('roadmaps', 'phases')
    op.drop_column('roadmaps', 'market_data')
    op.drop_column('roadmaps', 'target_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('target_jobs', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False))
    op.add_column('roadmaps', sa.Column('market_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('roadmaps', sa.Column('phases', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('roadmaps', 'summary')
    op.drop_index(op.f('ix_roadmap_phases_roadmap_id'), table_name='roadmap_phases')
    op.drop_table('roadmap_phases')
    # ### end Alembic commands ###
