"""add cv_text to interview_sessions

Revision ID: 35583ce4885e
Revises: b4bcd8b95aed
Create Date: 2026-03-22 17:06:54.967696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35583ce4885e'
down_revision: Union[str, Sequence[str], None] = 'b4bcd8b95aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('cv_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'cv_text')
    # ### end Alembic commands ###
