"""add coach_sessions table and user coach_usage fields

Revision ID: f1ccf024c728
Revises: 141656253150
Create Date: 2026-03-22 14:09:05.748076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1ccf024c728'
down_revision: Union[str, Sequence[str], None] = '141656253150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('cv_file_key', sa.String(length=500), nullable=True),
    sa.Column('cv_text', sa.Text(), nullable=True),
    sa.Column('compatibility_score', sa.Integer(), nullable=True),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=10), server_default='fr', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_sessions_user_id'), 'coach_sessions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('coach_usage_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('coach_usage_reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'coach_usage_reset_at')
    op.drop_column('users', 'coach_usage_count')
    op.drop_index(op.f('ix_coach_sessions_user_id'), table_name='coach_sessions')
    op.drop_table('coach_sessions')
    # ### end Alembic commands ###
