"""add cv_hash and job_description_hash to coach_sessions

Revision ID: f3782e62c0d8
Revises: 35583ce4885e
Create Date: 2026-03-22 17:51:13.154527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3782e62c0d8'
down_revision: Union[str, Sequence[str], None] = '35583ce4885e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_sessions', sa.Column('cv_hash', sa.String(length=64), nullable=True))
    op.add_column('coach_sessions', sa.Column('job_description_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach_sessions', 'job_description_hash')
    op.drop_column('coach_sessions', 'cv_hash')
    # ### end Alembic commands ###
